### PR TITLE
Fix translated feature lists

### PR DESCRIPTION
**Pull request by fpiesche**

### CODE REVIEW

**Comment by fpiesche** [comment]
@JakobDev is this the right approach?

**Comment by JakobDev** [comment]
No, as I said previous, the translation must come directly behind the original item like this:
```xml
<ul>
    <li>First item</li>
    <li xml:lang="de">First German item</li>
    <li xml:lang="pl">First Polish item</li>
    <li>Second item</li>
    <li xml:lang="de">Second German item</li>
    <li xml:lang="pl">Second Polish item</li>
</ul>
```
Having all translations as block is wrong.

**Comment by fpiesche** [comment]
> No, as I said previous, the translation must come directly behind the original item like this:
> 
> ```
> <ul>
>     <li>First item</li>
>     <li xml:lang="de">First German item</li>
>     <li xml:lang="pl">First Polish item</li>
>     <li>Second item</li>
>     <li xml:lang="de">Second German item</li>
>     <li xml:lang="pl">Second Polish item</li>
> </ul>
> ```
> 
> Having all translations as block is wrong.

Thanks for your help with this! Sorted it now :)

**Comment by JakobDev** [comment]
Now it is correct

**Comment by JakeSmarter** [comment]
https://github.com/JakeSmarter/io.github.theforceengine.tfe/commit/3dd33bb3e441b06bb91de36028caa52611e60941

**Comment by fpiesche** [comment]
@JakeSmarter would you mind submitting the same changes for the [upstream version of the file](https://github.com/fpiesche/TheForceEngine/blob/master/TheForceEngine/TheForceEngine.metainfo.xml) as well? The version here should be going away once a new upstream release version is tagged that we can use instead.

**Comment by JakeSmarter** [comment]
Sure, I do not mind. :wink: Had no time :watch: to do it.

**Comment by JakeSmarter** [comment]
@fpiesche Do you intend to drop the AppStream meta data in this repo in favor of upstream going forward?

**Comment by fpiesche** [comment]
> @fpiesche Do you intend to drop the AppStream meta data in this repo in favor of upstream going forward?

Yeah - Flathub generally request that all of that kind of data get submitted upstream; as I have done with the metadata here. The reason I've kept the local copy around is that there hasn't been a tagged release of TFE since my PR for the metadata has been merged, so the version of the repo used to build the Flatpak distribution (the `v1.09.540` tag) doesn't have this yet.

Once there's a new tagged release of TFE, Flathub's external data checker will automatically create a PR to update the Flatpak build at which point I'll modify the build manifest to use the `metainfo.xml` from upstream and remove the local copy.

**Comment by JakeSmarter** [comment]
> Once there's a new tagged release of TFE, Flathub's external data checker will automatically create a PR to update the Flatpak build at which point I'll modify the build manifest to use the `metainfo.xml` from upstream and remove the local copy.

Good, because I have made a little mistake in the meta data but I have fixed it upstream.

**Comment by JakeSmarter** [comment]
Btw, GNOME Software finally displays localized info for “The Force Engine” and it is a pleasure to look at!

Unfortunately, not so much on flathub.org because, like I have already mentioned, strangely enough Flathub website developers oppose displaying localized AppStream data for no rational reason.

**Pull request merged**
